USE heroku_3c6f88affb525fd;

SET FOREIGN_KEY_CHECKS = 0;
SET @@AUTO_INCREMENT_INCREMENT=1;

DROP TABLE IF EXISTS PARAMS;

CREATE TABLE PARAMS
(
  ID INTEGER NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(64) NOT NULL,
  VALUE VARCHAR(2048) DEFAULT NULL,
  
  PRIMARY KEY (ID),
  CONSTRAINT UC_NAME UNIQUE (NAME)
)
ENGINE = InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET = UTF8;

INSERT INTO PARAMS (NAME, VALUE) VALUES ('ACCESS_TOKEN', NULL);
INSERT INTO PARAMS (NAME, VALUE) VALUES ('REFRESH_TOKEN', NULL);

SET FOREIGN_KEY_CHECKS = 1;