DROP TABLE IF EXISTS PARAMS;

CREATE TABLE PARAMS
(
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL UNIQUE,
  VALUE VARCHAR(1000),
  CHANGED TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO PARAMS (NAME) VALUES ('ACCESS_TOKEN');
INSERT INTO PARAMS (NAME) VALUES ('REFRESH_TOKEN');
